### ISSUE TITLE
Really weird class name bugs the deobfuscator?

### ISSUE THREAD

**Issue by fikawka** [java-deobfuscator/deobfuscator#682] opened 2020-12-22 15:19 UTC
So i tried the detection thing, and i got that i need to use if i remember well illegalsignature remover.
I  used it the file lost like almost one mb.  But there is always a bug when i am deobfuscating:
Could not parse filename.class
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:259)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

Yeah this is really weird, and in winrar it shows like the class has no name. But in deobfuscator i get names and its really, really long with weird characters and it has like 100 words, in it extremely long. I might be wrong about 100 words, it might be 20 but its still extremely long.
After using class normalizer i got bug:
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.ClassNormalizer

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException
	at org.objectweb.asm.Type.getTypeInternal(Type.java:443)
	at org.objectweb.asm.Type.getType(Type.java:177)
	at org.objectweb.asm.commons.Remapper.mapDesc(Remapper.java:55)
	at org.objectweb.asm.commons.MethodRemapper.visitAnnotation(MethodRemapper.java:86)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:682)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:465)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer$$Lambda$30/384387360.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)S
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

After using detect thing on already removed illegalsignature it doesn't show anything.
In luyten i can't acces classes because it says: file not found. So the naming of these classes is really weird and is able to crash luyten and deobfuscator.
Nothing works against this file, probably because of their class obfuscation. Anything i can do?

**Comment by Janmm14** [comment] 2020-12-22 15:43
deobfuscator does not crash because of the class name, but because the class likely used some bug in asm as well.

Also nearly always 7zip is a better alternative to winrar, it comes completely free without a nasty warning of test time expiration.

**Comment by fikawka** [comment] 2020-12-22 15:51
Well, 7zip doesnt even say it contains any classes. But it does.

**Comment by fikawka** [comment] 2020-12-27 16:10
Someone knows how to fix it?? I have really no idea what to do

**Comment by fikawka** [comment] 2020-12-27 16:27
If it would help, i can send the file. Its public, anyone can download it

**Comment by fikawka** [comment] 2020-12-27 16:28
I mean its a minecraft client, but its public released on a website so i can send link for the website if i cant here

**Comment by Janmm14** [comment] 2020-12-27 17:12
nobody is required to help you, spamming comments wont help

**Comment by ItzSomebody** [comment] 2020-12-28 08:28
Sorry, this slipped through my notifications (I get a lot) so I didn't see it until now.

Feel free to mail a link to me (itzsomebody@protonmail.com) if you wish.

**Comment by ItzSomebody** [comment] 2021-01-04 22:01
@fikawka Sent me the JAR in question via email so here is my prognosis. The deobfuscator throws exceptions when attempting to parse bogus classfiles (entries ending in ".class" and/or filled with bogus data, corrupted constant pool entries, and/or encrypted classes) so this is intended behavior. 

As for the ClassNormalizer issue, I noticed that whatever obfuscator (or possibly many) used seems to fill the method signatures (used for generics information) with bogus strings. The illegal signature remover will help with that (signatures must be removed before).

I also noted there are various methods that seem to be string decryptors that compute xor keys based on the invocation context (which looks quite a lot like Allatori's), so you may have to write transformers to decrypt that first before remapping the file.

There are also a lot of what appear to be garbage annotations that generate large numbers of blank lines in a decompiler so that is something to look at as well.

Feel free to correct me if I'm wrong, but for now, I'll close the issue since I don't see one in particular. :)

**Closed by ItzSomebody** 2021-01-04 22:01 UTC
