### ISSUE TITLE
Error occurred while parsing the configuration file 

### ISSUE THREAD

**Issue by Sliden101** [java-deobfuscator/deobfuscator#817] opened 2021-08-29 05:49 UTC
Here is the error when I run  java -jar deobfuscator.jar --config detect.yml
 `[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occurred while parsing the configuration file
java.io.FileNotFoundException: detect.yml (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:307)
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:66)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)`
My config.yml file 
`input: input.jar
detect: true
`

**Comment by Janmm14** [comment] 2021-08-29 09:34
You told the program that your config file is named `detect.yml` and not `config.yml`

You also might want to look into using the [deobfuscator-gui](https://github.com/java-deobfuscator/deobfuscator-gui). Using it is significantly easier.

**Comment by ItzSomebody** [comment] 2021-09-20 04:00
Closing this as this is intended behavior.  Feel free to reply with any new information as needed.

**Closed by ItzSomebody** 2021-09-20 04:00 UTC
