### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ParityError** [java-deobfuscator/deobfuscator#941] opened 2022-10-16 21:05 UTC
I'm on macOS 12.6 and get the following error when attempting to execute the command below.

```
% java -jar deobfuscator.jar --config detect.yml
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:655)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:567)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:59)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
```

Please advise, thanks.

**Comment by Janmm14** [comment] 2022-10-16 21:46
Duplicate of #939

**Closed** 2022-11-05 21:47 UTC
