### ISSUE TITLE
Binscure Transformers?¿

### ISSUE THREAD

**Issue by ssllllll** [java-deobfuscator/deobfuscator#825] opened 2021-10-08 23:50 UTC
Can y'all try to add Binscure Transformers? The src code is public 🥺

**Comment by Janmm14** [comment] 2021-10-09 00:04
Duplicate of #822

**Comment by ssllllll** [comment] 2021-10-09 03:40
sex8

**Comment by ThisTestUser** [comment] 2021-10-11 02:39
A general Binscure transformer has been added, which should be able to reverse most obfuscation methods used by this obfuscator.

**Closed** 2021-10-31 05:09 UTC
