### ISSUE TITLE
deobfuscation failed

### ISSUE THREAD

**Issue by MouseHubMC** [java-deobfuscator/deobfuscator#898] opened 2022-04-20 19:10 UTC
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.javavm.mirrors.JavaClass.isPrimitive()" because "this.componentType" is null
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
	at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
	at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
	at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment] 2022-04-21 14:01
Duplicate of #897

Please see my comment there.

**Closed** 2022-07-08 07:25 UTC
